export const config = {
	App:{
		urls:{
			userinfo:'/User/userinfo'			
		},
		router:{},
		permission:{}
	},
	Home:{
		urls:{
			bannerList:'/index/bannerList',
			menuList:'/index/menuList',
			productDescList:'/index/productDescList',
			solutionList:'/index/solutionList',
			mediaNewsOv:'/index/mediaNewsOv',
			adList:'/index/adList',
			customeCaseList:'/index/customeCaseList',
			getDetail:'/index/getDetail'
		},
		router:{},
		permission:{}
	},
	Infomation:{
		urls:{
			allNewsList:'/index/allNewsList',
			getDetail:'/index/getDetail'			
		},
		router:{},
		permission:{}
	},
	Product:{
		urls:{
			productList:'/Index/productList'	
		},
		router:{},
		permission:{}
	},
	User:{
		urls:{
			loginvalid:'/user/loginvalid',
			logout:'/User/logout',
			register:'/User/register',
			forgetPasswrd:'/user/forgetPasswrd',
			sendCode:'/user/sendCode'
		},
		router:{},
		permission:{}
		
	}
}